---

wiki_db_admin_user     : wikiadmin
wiki_db_admin_password : "{{ lookup('aws_ssm', 'wiki-db-password', region='us-east-1' ) }}"
wiki_db_app_user       : wiki
wiki_db_app_password   : "{{ lookup('password', '~/.wiki_db_app_password') }}"
wiki_db_hosts          : "{{ groups['wiki-db'] | map('extract', hostvars, 'ansible_host') | list }}"
